INSERT INTO DevTecDB.DBO.Cliente(PrimeiroNome,Sobrenome,Email,Telefone,Documento,CodigoEndereco,CodigoTipoPessoa,SiglaTipoPessoa)
SELECT  [column1]
      ,[column2]
      ,[column3]
      ,[column4]
      ,[column5]
      ,[column6]
      ,[column7]
      ,[column8]
  FROM [DevTecDB].[dbo].[RAW_Insert_Cliente]